import {
  Activity,
  Anchor,
  Award,
  Baby,
  Backpack,
  Bandage,
  Banknote,
  BanknoteArrowUp,
  Battery,
  Bed,
  Beer,
  Bell,
  Bike,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  Clapperboard,
  Clock,
  Cloud,
  Club,
  Coffee,
  Coins,
  Compass,
  Cookie,
  CreditCard,
  Crown,
  Diamond,
  Dice5,
  Dog,
  Drama,
  Droplet,
  Dumbbell,
  Factory,
  Film,
  Flag,
  Flame,
  Flower,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  House,
  IceCreamCone,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  Luggage,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageCircle,
  Monitor,
  Mountain,
  Music,
  Package,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneTakeoff,
  Plug,
  Printer,
  Puzzle,
  Receipt,
  Recycle,
  Refrigerator,
  Rocket,
  Scissors,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sofa,
  Soup,
  Spade,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Target,
  Tent,
  Thermometer,
  Ticket,
  Timer,
  TrainFront,
  TreePine,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  User,
  UserRound,
  Users,
  Utensils,
  Wallet,
  WashingMachine,
  Watch,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Same key sets as backend/src/budgets/budget-category-visuals.ts -- keep
// both lists in sync by hand. See that file's header comment for why the
// first 18 keys (shopping..service) are frozen and everything after is a
// large, intentionally uncapped addition -- the picker below is a
// scrollable, searchable grid now, not a fixed 3-row-of-6, so there's no
// reason to keep the list small.
export const BUDGET_CATEGORY_ICONS = [
  "shopping",
  "home",
  "car",
  "food",
  "entertainment",
  "health",
  "travel",
  "education",
  "clothing",
  "salary",
  "commission",
  "bonus",
  "rental",
  "interest",
  "investment",
  "dividend",
  "gift",
  "service",
  "shopping-bag",
  "shopping-cart",
  "gem",
  "sparkles",
  "watch",
  "glasses",
  "shirt",
  "house",
  "bed",
  "sofa",
  "lamp",
  "refrigerator",
  "washing-machine",
  "plug",
  "lightbulb",
  "thermometer",
  "wifi",
  "droplet",
  "flame",
  "bus",
  "train-front",
  "bike",
  "fuel",
  "truck",
  "ship",
  "anchor",
  "plane",
  "plane-takeoff",
  "luggage",
  "map-pin",
  "compass",
  "tent",
  "mountain",
  "waves",
  "globe",
  "map",
  "utensils",
  "coffee",
  "pizza",
  "cake",
  "cookie",
  "beer",
  "wine",
  "soup",
  "ice-cream-cone",
  "cake-slice",
  "drama",
  "clapperboard",
  "music",
  "gamepad-2",
  "tv",
  "film",
  "ticket",
  "puzzle",
  "dice-5",
  "dumbbell",
  "heart-pulse",
  "stethoscope",
  "pill",
  "activity",
  "syringe",
  "bandage",
  "graduation-cap",
  "book-open",
  "backpack",
  "pencil",
  "heart",
  "baby",
  "dog",
  "cat",
  "paw-print",
  "users",
  "user",
  "user-round",
  "handshake",
  "flower",
  "flower-2",
  "leaf",
  "tree-pine",
  "sprout",
  "sun",
  "cloud",
  "snowflake",
  "wrench",
  "paintbrush",
  "palette",
  "scissors",
  "key",
  "lock",
  "shield",
  "wallet",
  "banknote",
  "banknote-arrow-up",
  "coins",
  "piggy-bank",
  "hand-coins",
  "credit-card",
  "receipt",
  "calculator",
  "percent",
  "trending-up",
  "trending-down",
  "landmark",
  "building",
  "building-2",
  "factory",
  "store",
  "briefcase",
  "trophy",
  "medal",
  "crown",
  "target",
  "rocket",
  "party-popper",
  "smartphone",
  "laptop",
  "monitor",
  "headphones",
  "camera",
  "printer",
  "package",
  "recycle",
  "battery",
  "spade",
  "club",
  "diamond",
  "star",
  "zap",
  "phone",
  "mail",
  "message-circle",
  "bell",
  "calendar",
  "clock",
  "timer",
  "flag",
] as const;

// Original 8 plus a few more distinct Tailwind hues.
export const BUDGET_CATEGORY_COLORS = [
  "blue",
  "green",
  "purple",
  "orange",
  "pink",
  "yellow",
  "red",
  "indigo",
  "teal",
  "cyan",
  "violet",
  "lime",
] as const;

const ICON_COMPONENTS: Record<(typeof BUDGET_CATEGORY_ICONS)[number], LucideIcon> = {
  shopping: ShoppingBag,
  home: Home,
  car: Car,
  food: Utensils,
  entertainment: Clapperboard,
  health: Heart,
  travel: Plane,
  education: Backpack,
  clothing: Shirt,
  salary: Wallet,
  commission: Percent,
  bonus: Award,
  rental: Building2,
  interest: TrendingUp,
  investment: PiggyBank,
  dividend: Landmark,
  gift: Gift,
  service: Briefcase,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  gem: Gem,
  sparkles: Sparkles,
  watch: Watch,
  glasses: Glasses,
  shirt: Shirt,
  house: House,
  bed: Bed,
  sofa: Sofa,
  lamp: Lamp,
  refrigerator: Refrigerator,
  "washing-machine": WashingMachine,
  plug: Plug,
  lightbulb: Lightbulb,
  thermometer: Thermometer,
  wifi: Wifi,
  droplet: Droplet,
  flame: Flame,
  bus: Bus,
  "train-front": TrainFront,
  bike: Bike,
  fuel: Fuel,
  truck: Truck,
  ship: Ship,
  anchor: Anchor,
  plane: Plane,
  "plane-takeoff": PlaneTakeoff,
  luggage: Luggage,
  "map-pin": MapPin,
  compass: Compass,
  tent: Tent,
  mountain: Mountain,
  waves: Waves,
  globe: Globe,
  map: Map,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  cake: Cake,
  cookie: Cookie,
  beer: Beer,
  wine: Wine,
  soup: Soup,
  "ice-cream-cone": IceCreamCone,
  "cake-slice": CakeSlice,
  drama: Drama,
  clapperboard: Clapperboard,
  music: Music,
  "gamepad-2": Gamepad2,
  tv: Tv,
  film: Film,
  ticket: Ticket,
  puzzle: Puzzle,
  "dice-5": Dice5,
  dumbbell: Dumbbell,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  activity: Activity,
  syringe: Syringe,
  bandage: Bandage,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  backpack: Backpack,
  pencil: Pencil,
  heart: Heart,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  "paw-print": PawPrint,
  users: Users,
  user: User,
  "user-round": UserRound,
  handshake: Handshake,
  flower: Flower,
  "flower-2": Flower2,
  leaf: Leaf,
  "tree-pine": TreePine,
  sprout: Sprout,
  sun: Sun,
  cloud: Cloud,
  snowflake: Snowflake,
  wrench: Wrench,
  paintbrush: Paintbrush,
  palette: Palette,
  scissors: Scissors,
  key: Key,
  lock: Lock,
  shield: Shield,
  wallet: Wallet,
  banknote: Banknote,
  "banknote-arrow-up": BanknoteArrowUp,
  coins: Coins,
  "piggy-bank": PiggyBank,
  "hand-coins": HandCoins,
  "credit-card": CreditCard,
  receipt: Receipt,
  calculator: Calculator,
  percent: Percent,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  landmark: Landmark,
  building: Building,
  "building-2": Building2,
  factory: Factory,
  store: Store,
  briefcase: Briefcase,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  target: Target,
  rocket: Rocket,
  "party-popper": PartyPopper,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  headphones: Headphones,
  camera: Camera,
  printer: Printer,
  package: Package,
  recycle: Recycle,
  battery: Battery,
  spade: Spade,
  club: Club,
  diamond: Diamond,
  star: Star,
  zap: Zap,
  phone: Phone,
  mail: Mail,
  "message-circle": MessageCircle,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  flag: Flag,
};

// Solid background + white icon, matching the reference design's filled
// category badges (rather than this app's usual "colored icon on neutral
// background" convention elsewhere) -- budget categories are meant to read
// as distinct, at-a-glance tags.
const COLOR_CLASSES: Record<(typeof BUDGET_CATEGORY_COLORS)[number], string> = {
  blue: "bg-blue-600",
  green: "bg-emerald-600",
  purple: "bg-purple-600",
  orange: "bg-orange-500",
  pink: "bg-pink-600",
  yellow: "bg-amber-500",
  red: "bg-red-600",
  indigo: "bg-indigo-600",
  teal: "bg-teal-600",
  cyan: "bg-cyan-600",
  violet: "bg-violet-600",
  lime: "bg-lime-500",
};

// Friendly label per icon key, for a hover tooltip AND (now that the picker
// is searchable) the text a search matches against -- the keys themselves
// are internal-only, e.g. "rental" for what a user should see as "Rental
// Income".
const ICON_LABELS: Record<(typeof BUDGET_CATEGORY_ICONS)[number], string> = {
  shopping: "Shopping",
  home: "Home",
  car: "Car / Transport",
  food: "Food & Dining",
  entertainment: "Entertainment",
  health: "Health",
  travel: "Travel",
  education: "Education",
  clothing: "Clothing",
  salary: "Salary",
  commission: "Commission",
  bonus: "Bonus",
  rental: "Rental Income",
  interest: "Interest / Profit Income",
  investment: "Investment Income",
  dividend: "Dividend Income",
  gift: "Gift",
  service: "Service Income",
  "shopping-bag": "Shopping Bag",
  "shopping-cart": "Shopping Cart",
  gem: "Gem / Luxury",
  sparkles: "Sparkles",
  watch: "Watch",
  glasses: "Glasses",
  shirt: "Shirt",
  house: "House / Rent",
  bed: "Bed",
  sofa: "Sofa",
  lamp: "Lamp",
  refrigerator: "Refrigerator",
  "washing-machine": "Laundry",
  plug: "Plug",
  lightbulb: "Lightbulb",
  thermometer: "Thermometer",
  wifi: "Wifi",
  droplet: "Droplet",
  flame: "Flame",
  bus: "Bus",
  "train-front": "Train",
  bike: "Bike",
  fuel: "Fuel",
  truck: "Truck",
  ship: "Ship",
  anchor: "Anchor",
  plane: "Plane",
  "plane-takeoff": "Flight",
  luggage: "Luggage",
  "map-pin": "Map Pin",
  compass: "Compass",
  tent: "Tent",
  mountain: "Mountain",
  waves: "Waves",
  globe: "Globe",
  map: "Map",
  utensils: "Utensils",
  coffee: "Coffee",
  pizza: "Pizza",
  cake: "Cake",
  cookie: "Cookie",
  beer: "Beer",
  wine: "Wine",
  soup: "Soup",
  "ice-cream-cone": "Ice Cream",
  "cake-slice": "Dessert",
  drama: "Drama",
  clapperboard: "Clapperboard",
  music: "Music",
  "gamepad-2": "Gaming",
  tv: "TV",
  film: "Film",
  ticket: "Ticket",
  puzzle: "Puzzle",
  "dice-5": "Games / Lottery",
  dumbbell: "Dumbbell",
  "heart-pulse": "Fitness / Wellness",
  stethoscope: "Stethoscope",
  pill: "Pill",
  activity: "Activity",
  syringe: "Syringe",
  bandage: "Bandage",
  "graduation-cap": "Graduation Cap",
  "book-open": "Books",
  backpack: "Backpack",
  pencil: "Pencil",
  heart: "Heart",
  baby: "Baby",
  dog: "Dog",
  cat: "Cat",
  "paw-print": "Pet Care",
  users: "Users",
  user: "User",
  "user-round": "Family Member",
  handshake: "Handshake",
  flower: "Flower",
  "flower-2": "Flower (Alt)",
  leaf: "Leaf",
  "tree-pine": "Nature / Garden",
  sprout: "Sprout",
  sun: "Sun",
  cloud: "Cloud",
  snowflake: "Snowflake",
  wrench: "Wrench",
  paintbrush: "Paintbrush",
  palette: "Palette",
  scissors: "Scissors",
  key: "Key",
  lock: "Lock",
  shield: "Shield",
  wallet: "Wallet",
  banknote: "Banknote",
  "banknote-arrow-up": "Raise / Bonus",
  coins: "Coins",
  "piggy-bank": "Savings",
  "hand-coins": "Cash Tips",
  "credit-card": "Credit Card",
  receipt: "Receipt",
  calculator: "Calculator",
  percent: "Percent",
  "trending-up": "Investment Growth",
  "trending-down": "Loss / Depreciation",
  landmark: "Landmark",
  building: "Building",
  "building-2": "Office Building",
  factory: "Factory",
  store: "Store",
  briefcase: "Briefcase",
  trophy: "Trophy / Incentive",
  medal: "Medal / Award",
  crown: "Crown / Premium",
  target: "Target",
  rocket: "Rocket / Growth",
  "party-popper": "Celebration",
  smartphone: "Smartphone",
  laptop: "Laptop",
  monitor: "Monitor",
  headphones: "Headphones",
  camera: "Camera",
  printer: "Printer",
  package: "Package",
  recycle: "Recycle",
  battery: "Battery",
  spade: "Spade",
  club: "Club",
  diamond: "Diamond",
  star: "Star",
  zap: "Zap",
  phone: "Phone",
  mail: "Mail",
  "message-circle": "Messaging",
  bell: "Bell",
  calendar: "Calendar",
  clock: "Clock",
  timer: "Timer",
  flag: "Flag",
};

export function budgetCategoryIcon(icon: string): LucideIcon {
  return ICON_COMPONENTS[icon as (typeof BUDGET_CATEGORY_ICONS)[number]] ?? ShoppingBag;
}

export function budgetCategoryIconLabel(icon: string): string {
  return ICON_LABELS[icon as (typeof BUDGET_CATEGORY_ICONS)[number]] ?? icon;
}

export function budgetCategoryColorClass(color: string): string {
  return COLOR_CLASSES[color as (typeof BUDGET_CATEGORY_COLORS)[number]] ?? "bg-neutral-500";
}

// Same colors as COLOR_CLASSES above, as actual hex values -- a
// conic-gradient wedge (Financial Reports' category donut charts) needs a
// real color, not a Tailwind class name.
const COLOR_HEX: Record<(typeof BUDGET_CATEGORY_COLORS)[number], string> = {
  blue: "#2563eb",
  green: "#059669",
  purple: "#9333ea",
  orange: "#f97316",
  pink: "#db2777",
  yellow: "#f59e0b",
  red: "#dc2626",
  indigo: "#4f46e5",
  teal: "#0d9488",
  cyan: "#0891b2",
  violet: "#7c3aed",
  lime: "#84cc16",
};

export function budgetCategoryHex(color: string): string {
  return COLOR_HEX[color as (typeof BUDGET_CATEGORY_COLORS)[number]] ?? "#a3a3a3";
}

// EXPENSE: <70% green, 70-99% amber, >=100% red -- matches the reference's
// Food & Dining (70%, green) vs Housing/Transportation (80%/90%, amber)
// examples; going over a spending LIMIT is bad. INCOME is the opposite --
// exceeding an income GOAL is good news, so it never turns red/amber.
export function budgetProgressColorClass(percent: number, type: "EXPENSE" | "INCOME" = "EXPENSE"): string {
  if (type === "INCOME") return "bg-brand-primary";
  if (percent >= 100) return "bg-brand-danger";
  if (percent >= 70) return "bg-amber-500";
  return "bg-brand-primary";
}

// Common Income Planning category names -> a fitting icon, so typing one of
// these well-known names auto-selects a sensible icon instead of leaving
// whatever was previously selected. Exact, case-insensitive match only (no
// fuzzy/partial matching) -- BudgetCategoryModal only applies this while the
// user hasn't manually touched the icon picker in the current session, so a
// deliberate pick is never silently overridden.
const INCOME_ICON_SUGGESTIONS: Record<string, (typeof BUDGET_CATEGORY_ICONS)[number]> = {
  salary: "salary",
  commission: "commission",
  bonus: "bonus",
  "rental income": "rental",
  "interest/profit income": "interest",
  "interest income": "interest",
  "profit income": "interest",
  "investment income": "investment",
  "dividend income": "dividend",
  gift: "gift",
  "service income": "service",
};

export function suggestIconForCategoryName(name: string): (typeof BUDGET_CATEGORY_ICONS)[number] | null {
  return INCOME_ICON_SUGGESTIONS[name.trim().toLowerCase()] ?? null;
}
